name: Deploy Infrastructure

on:
  push:
    branches:
      - 'main'
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  terraform_apply:
    uses: ./templates/terraform.yml
    with:
      terraform_command: apply
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
      STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      TFSTATE_KEY: ${{ secrets.TFSTATE_KEY }}