name: Build and Deploy Web Analytics Application

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - 'Dockerfile'

permissions:
  id-token: write
  contents: read

env:
  DOCKER_IMAGE_NAME: 'web-analytics-app'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    - name: Authenticate with Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_SERVER }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker image for security scanning
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: ${{ secrets.ACR_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:latest
        load: true

    - name: Scan Docker image for security vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.ACR_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:latest
        format: 'table'
        exit-code: '0'
        severity: 'CRITICAL,HIGH'

    - name: Build and push Docker image to Azure Container Registry
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.ACR_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.run_number }}
          ${{ secrets.ACR_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:latest