name: Validate Infrastructure

on:
  pull_request:
    branches:
      - 'main'
      - 'dev'
    paths:
      - 'terraform/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
  STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
  TFSTATE_KEY: ${{ secrets.TFSTATE_KEY }}
  TF_VAR_postgresql_administrator_password: ${{ secrets.POSTGRESQL_ADMIN_PASSWORD }}

jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Terraform Validate
        uses: ./.github/actions/terraform
        with:
          terraform_command: validate

  terraform_plan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: terraform_validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Terraform Plan
        uses: ./.github/actions/terraform
        with:
          terraform_command: plan

  security_scanning:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: terraform_plan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Security Scanning
        uses: ./.github/actions/security
        with:
          working_directory: terraform/ 