name: Deploy Infrastructure

on:
  push:
    branches:
      - 'main'
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Terraform Apply
        uses: ./.github/actions/terraform
        with:
          terraform_command: apply
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
          STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
          TFSTATE_KEY: ${{ secrets.TFSTATE_KEY }}
          TF_VAR_postgresql_administrator_password: ${{ secrets.POSTGRESQL_ADMIN_PASSWORD }}